using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GooseGames.Services.JustOne
{
    public static class TemporaryWordsList
    {
        public static List<string> GetWords(int numberOfWords)
        {
            var numberOfWordsTotal = Words.Count;
            if (numberOfWords > numberOfWordsTotal)
            {
                throw new ArgumentOutOfRangeException(nameof(numberOfWords));
            }

            var random = new Random();

            var results = new List<string>();

            while (results.Count < numberOfWords)
            {
                string item = Words[random.Next(numberOfWordsTotal)];
                if (!results.Contains(item))
                {
                    results.Add(item);
                }
            }

            return results;
        }

        public static List<string> Words = new List<string>
        {
            "africa",
            "agent",
            "air",
            "alien",
            "amazon",
            "angel",
            "antarctica",
            "apple",
            "arm",
            "back",
            "band",
            "bank",
            "bark",
            "beach",
            "belt",
            "berlin",
            "berry",
            "board",
            "bond",
            "boom",
            "bow",
            "box",
            "bug",
            "canada",
            "capital",
            "cell",
            "center",
            "china",
            "chocolate",
            "circle",
            "club",
            "compound",
            "copper",
            "crash",
            "cricket",
            "cross",
            "death",
            "dice",
            "dinosaur",
            "doctor",
            "dog",
            "dress",
            "dwarf",
            "eagle",
            "egypt",
            "engine",
            "england",
            "europe",
            "eye",
            "fair",
            "fall",
            "fan",
            "field",
            "file",
            "film",
            "fish",
            "flute",
            "fly",
            "forest",
            "fork",
            "france",
            "gas",
            "ghost",
            "giant",
            "glass",
            "glove",
            "gold",
            "grass",
            "greece",
            "green",
            "ham",
            "head",
            "himalaya",
            "hole",
            "hood",
            "hook",
            "human",
            "horseshoe",
            "hospital",
            "hotel",
            "ice",
            "ice cream",
            "india",
            "iron",
            "ivory",
            "jam",
            "jet",
            "jupiter",
            "kangaroo",
            "ketchup",
            "kid",
            "king",
            "kiwi",
            "knife",
            "knight",
            "lab",
            "lap",
            "laser",
            "lawyer",
            "lead",
            "lemon",
            "limousine",
            "leadlock",
            "log",
            "mammoth",
            "maple",
            "march",
            "mass",
            "mercury",
            "millionaire",
            "model",
            "mole",
            "moscow",
            "mouth",
            "mug",
            "needle",
            "net",
            "new york",
            "night",
            "note",
            "novel",
            "nurse",
            "nut",
            "oil",
            "olive",
            "olympus",
            "opera",
            "orange",
            "paper",
            "park",
            "part",
            "paste",
            "phoenix",
            "piano",
            "telescope",
            "teacher",
            "switch",
            "swing",
            "sub",
            "stick",
            "staff",
            "stadium",
            "sprint",
            "spike",
            "snowman",
            "slip",
            "shot",
            "shadow",
            "server",
            "ruler",
            "row",
            "rose",
            "root",
            "rome",
            "rock",
            "robot",
            "robin",
            "revolution",
            "rat",
            "racket",
            "queen",
            "press",
            "port",
            "pilot",
            "time",
            "tooth",
            "tower",
            "truck",
            "triangle",
            "trip",
            "turkey",
            "undertaker",
            "unicorn",
            "vacuum",
            "van",
            "wake",
            "wall",
            "war",
            "washer",
            "washington",
            "water",
            "wave",
            "well",
            "whale",
            "whip",
            "worm",
            "yard"
        };
    }
}
